// @ts-check
import { defineConfig } from "astro/config";
import tailwind from "@astrojs/tailwind";
import sitemap from "@astrojs/sitemap";
import mdx from "@astrojs/mdx";
import cloudflare from "@astrojs/cloudflare";

export default defineConfig({
  adapter: cloudflare({
    platformProxy: { enabled: true },
    imageService: "compile",
  }),
  site: "https://reallyniceday.com",
  integrations: [
    mdx(),
    tailwind(),
    sitemap({
      filter: (page) => {
        const path = new URL(page).pathname;
        // Include homepage, /en/, /about/, and all /zh-tw/ & /en/ post pages
        // Exclude /[slug]/ redirect pages (generated by src/pages/[slug].astro)
        return (
          path === "/" ||
          path.startsWith("/zh-tw/") ||
          path.startsWith("/en/") ||
          path === "/about/"
        );
      },
    }),
  ],
  redirects: {
    // Old Ghost URLs -> new i18n URLs
    // Chinese posts were at /[slug]/, now at /zh-tw/[slug]/
    // English posts were at /en/[slug]-en/, now at /en/[slug]-en/
    // Add specific redirects here as needed
  },
});
