name = "astro-blog"
compatibility_date = "2026-02-11"

[assets]
directory = "./dist"

[env.production.vars]
GA_ID = "G-RR1ZEHQSST"
CF_TOKEN = "62e90558ddd846bbbd9d53ab6e550b09"
POSTHOG_KEY = "phc_w0wwPJmYGfVKQPdJfTsNWdKMtq2MkQg2fn6YrBEf06b"
POSTHOG_HOST = "https://us.i.posthog.com"
UMAMI_ID = "4a26a184-18ca-4441-9e61-2076e938ec32"
